# Generated by Django 5.0.7 on 2026-07-21 14:55

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_role_userrole"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "ordering": ["user", "role"],
                "verbose_name": "Rol de Usuario",
                "verbose_name_plural": "Roles de Usuarios",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.managers.UserManager()),
            ],
        ),
    ]
