# Generated by Django 5.0.7 on 2026-07-07 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0002_institution_type_alter_institution_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="programs/images/"
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(default="#1E3A8A", max_length=20)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("DIPLOMADO", "Diplomado"),
                            ("CURSO", "Curso"),
                            ("LICENCIATURA", "Licenciatura"),
                            ("SEMINARIO", "Seminario"),
                            ("TALLER", "Taller"),
                            ("DEVOCIONAL", "Devocional"),
                            ("PLAN_LECTURA", "Plan de Lectura"),
                        ],
                        default="CURSO",
                        max_length=30,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BASICO", "Básico"),
                            ("INTERMEDIO", "Intermedio"),
                            ("AVANZADO", "Avanzado"),
                            ("ESPECIALIZADO", "Especializado"),
                        ],
                        default="BASICO",
                        max_length=30,
                    ),
                ),
                ("duration_value", models.PositiveIntegerField(default=1)),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("DIAS", "Días"),
                            ("SEMANAS", "Semanas"),
                            ("MESES", "Meses"),
                            ("ANIOS", "Años"),
                        ],
                        default="SEMANAS",
                        max_length=20,
                    ),
                ),
                ("academic_hours", models.PositiveIntegerField(default=0)),
                ("certificate_enabled", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa Académico",
                "verbose_name_plural": "Programas Académicos",
                "ordering": ["name"],
            },
        ),
    ]
