# Generated by Django 5.0.7 on 2026-06-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="type",
            field=models.CharField(
                choices=[
                    ("church", "Iglesia"),
                    ("seminary", "Seminario"),
                    ("institute", "Instituto Bíblico"),
                    ("university", "Universidad"),
                ],
                default="church",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
