# Generated by Django 5.0.7 on 2026-07-07 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("PDF", "PDF"),
                            ("AUDIO", "Audio"),
                            ("IMAGE", "Imagen"),
                            ("FILE", "Archivo"),
                            ("LINK", "Enlace"),
                            ("PRESENTATION", "Presentación"),
                        ],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="resources/files/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="resources/thumbnails/"
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_downloadable", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["lesson", "order"],
            },
        ),
    ]
