# Generated by Django 5.0.7 on 2026-07-07 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("READING", "Lectura"),
                            ("AUDIO", "Audio"),
                            ("PDF", "PDF"),
                            ("QUIZ", "Evaluación"),
                            ("ASSIGNMENT", "Actividad"),
                        ],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("estimated_minutes", models.PositiveIntegerField(default=0)),
                ("is_preview", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="modules.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lección",
                "verbose_name_plural": "Lecciones",
                "ordering": ["module", "order", "name"],
            },
        ),
    ]
